version: '3'

services:
  api:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /app
    ports:
      - 8081:8081
    env_file:
      - .env
    volumes:
      - ./:/app/
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
  db:
    image: postgres:14.7
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
  redis-cache:
    container_name: "redis-cache"
    image: "redis:6.2-alpine"
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - default


networks:
  default:

volumes:
  db_data:
  redis.conf: